name = "gossip-anonymous"
pages_build_output_dir = "./public"
compatibility_date = "2025-09-01"

[[d1_databases]]
binding = "DB"
database_name = "gossip-stories-db"
database_id = "91f131eb-b545-441e-92bf-0805dc34a71e"
migrations_dir = "migrations"
